## Use workflows from ninenines/ci.erlang.mk to test Cowboy.

name: Check Cowboy

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      ## Every Monday at 2am.
      - cron: 0 2 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    if: ${{ !cancelled() }}
    uses: ninenines/ci.erlang.mk/.github/workflows/ci.yaml@master

  examples:
    name: Check examples
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install latest Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: '> 0'

    - name: Run ct-examples
      run: make ct-examples

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Common Test logs (examples)
        path: |
          logs/
          !logs/**/log_private
